assuming_all_steps

diff --git a/content/opt/run b/content/opt/run
--- a/content/opt/run
+++ b/content/opt/run
@@ -7,31 +7,23 @@ initfile=/etc/rundeck.init
 chmod 1777 /tmp
 
 if [[ -n "${RUNDECK_GID}" && -n "${RUNDECK_UID}" ]]; then
-  echo "Ajustando usuario do rundeck para  ${RUNDECK_UID}:${RUNDECK_GID}"
+  echo "Setting rundeck account to ${RUNDECK_UID}:${RUNDECK_GID}"
   groupmod -o -g ${RUNDECK_GID} rundeck
   usermod -o -u ${RUNDECK_UID} -g ${RUNDECK_GID} rundeck
 fi
 
 # chown directories and files that might be coming from volumes
-echo "=>Ajustando permissões de arquivos em volumes persistentes"
 find /etc/rundeck /var/rundeck /var/log/rundeck \
   /var/lib/rundeck /opt/rundeck-defaults /tmp/rundeck \
   \! -user rundeck -exec chown -R rundeck:rundeck {} \;
 chmod -R 750 /tmp/rundeck
 
-# Plugins
-if ls /opt/rundeck-plugins/* 1> /dev/null 2>&1; then
-   echo "=>Instalando plugins montados em /opt/rundeck-plugins"
-   cp -Rf /opt/rundeck-plugins/* /var/lib/rundeck/libext/
-   chown -R rundeck:rundeck /var/lib/rundeck/libext
-fi
-
 
 if [ ! -f "${initfile}" ]; then
-   SERVER_URL=${SERVER_URL:-"https://0.0.0.0:4443"}
-   SERVER_HOSTNAME=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $1}')
-   SERVER_PROTO=$(echo ${SERVER_URL} | awk -F/ '{print $1}' | awk -F: '{print $1}')
-   SERVER_PORT=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $2}')
+  SERVER_URL=${SERVER_URL:-"https://0.0.0.0:4443"}
+  SERVER_HOSTNAME=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $1}')
+  SERVER_PROTO=$(echo ${SERVER_URL} | awk -F/ '{print $1}' | awk -F: '{print $1}')
+  SERVER_PORT=$(echo ${SERVER_URL} | awk -F/ '{print $3}' | awk -F: '{print $2}')
    if [ -z ${SERVER_PORT} ]; then
       # No port in SERVER_URL so assume 443 for HTTPS or 80 otherwise
       if [ ${SERVER_PROTO} == "https" ]; then
@@ -57,49 +49,31 @@ if [ ! -f "${initfile}" ]; then
   if [ -f /run/secrets/RUNDECK_ADMIN_PASSWORD ]; then
     RUNDECK_ADMIN_PASSWORD=$(< /run/secrets/RUNDECK_ADMIN_PASSWORD)
   fi
+  if [ -f /run/secrets/RUNDECK_STORAGE_PASSWORD ]; then
+    RUNDECK_STORAGE_PASSWORD=$(< /run/secrets/RUNDECK_STORAGE_PASSWORD)
+  fi
 
-   DATABASE_URL=${DATABASE_URL:-"jdbc:mysql://db/rundeck?autoReconnect=true"}
-   MYSQL_DATABASE=${DATABASE_NAME:-"rundeck"}
-   DATABASE_DRIVER=${DATABASE_DRIVER:-"org.mariadb.jdbc.Driver"}
-   RUNDECK_USER=${RUNDECK_USER:-"rundeck"}
-   RUNDECK_PASSWORD=${RUNDECK_PASSWORD:-$(pwgen -s 15 1)}
-   DATABASE_ADMIN_PASSWORD=${DATABASE_ADMIN_PASSWORD:-${RUNDECK_PASSWORD}}
-   DATABASE_ADMIN_USER=${DATABASE_ADMIN_USER:-rundeck}
-   RUNDECK_STORAGE_PROVIDER=${RUNDECK_STORAGE_PROVIDER:-"file"}
-   RUNDECK_PROJECT_STORAGE_TYPE=${RUNDECK_PROJECT_STORAGE_TYPE:-"file"}
-   #NO_LOCAL_MYSQL=${NO_LOCAL_MYSQL:-"false"}
-   SKIP_DATABASE_SETUP=${SKIP_DATABASE_SETUP:-"true"}
-   LOGIN_MODULE=${LOGIN_MODULE:-"RDpropertyfilelogin"}
-   JAAS_CONF_FILE=${JAAS_CONF_FILE:-"jaas-loginmodule.conf"}
-   KEYSTORE_PASS=${KEYSTORE_PASS:-"adminadmin"}
-   TRUSTSTORE_PASS=${TRUSTSTORE_PASS:-${KEYSTORE_PASS}}
-   CLUSTER_MODE=${CLUSTER_MODE:-"false"}
+  DATABASE_URL=${DATABASE_URL:-"jdbc:mysql://localhost/rundeckdb?autoReconnect=true"}
+  DATABASE_DRIVER=${DATABASE_DRIVER:-"org.mariadb.jdbc.Driver"}
+  RUNDECK_USER=${RUNDECK_USER:-"rundeck"}
+  RUNDECK_PASSWORD=${RUNDECK_PASSWORD:-$(pwgen -s 15 1)}
+  DATABASE_ADMIN_PASSWORD=${DATABASE_ADMIN_PASSWORD:-${RUNDECK_PASSWORD}}
+  DATABASE_ADMIN_USER=${DATABASE_ADMIN_USER:-rundeck}
+  RUNDECK_STORAGE_PROVIDER=${RUNDECK_STORAGE_PROVIDER:-"db"}
+  NO_LOCAL_MYSQL=${NO_LOCAL_MYSQL:-"false"}
+  SKIP_DATABASE_SETUP=${SKIP_DATABASE_SETUP:-"false"}
+  LOGIN_MODULE=${LOGIN_MODULE:-"RDpropertyfilelogin"}
+  JAAS_CONF_FILE=${JAAS_CONF_FILE:-"jaas-loginmodule.conf"}
+  KEYSTORE_PASS=${KEYSTORE_PASS:-"adminadmin"}
+  TRUSTSTORE_PASS=${TRUSTSTORE_PASS:-${KEYSTORE_PASS}}
+  CLUSTER_MODE=${CLUSTER_MODE:-"false"}
 
-   update_user_password () {
-      (
-      echo "UPDATE mysql.user SET password=PASSWORD('${2}') WHERE user='${1}';"
-      echo "FLUSH PRIVILEGES;"
-      echo "quit"
-      ) |
-      mysql
-   }
 
-   echo "=>Inicializando rundeck - Isso pode demorar um pouco"
-
-    # SSH
-    if ls /tmp/rundeck/ssh/* 1> /dev/null 2>&1; then
-      echo "=>Configurando SSH KEYS em /tmp/rundeck/ssh"
-      chown -R rundeck:rundeck /tmp/rundeck/ssh/*
-      cp -rp /tmp/rundeck/ssh/* /var/lib/rundeck/.ssh/
-      chmod 0600 /var/lib/rundeck/.ssh/*
-      chmod 0644 /var/lib/rundeck/.ssh/*.pub
-    fi
-    
+   echo "=>Initializing rundeck - This may take a few minutes"
    if [ ! -f /var/lib/rundeck/.ssh/id_rsa ]; then
-       echo "=>Voce nao me passou nenhuma chave ssh. Gerando chaves ssh agora!"
+       echo "=>Generating rundeck key"
        sudo -u rundeck ssh-keygen -t rsa -b 4096 -f /var/lib/rundeck/.ssh/id_rsa -N ''
    fi
-
 
    # copy rundeck defaults
    if [ ! "$(ls -1A /etc/rundeck|grep -v lost+found)" ]; then
@@ -107,17 +81,8 @@ if [ ! -f "${initfile}" ]; then
       chown -R rundeck:rundeck /etc/rundeck
    fi
 
-    # ACLS
-    if ls /tmp/rundeck/ACLS/* 1> /dev/null 2>&1; then
-      echo "=>Configurando ACLS em /tmp/rundeck/ACLS"
-      chown -R rundeck:rundeck /tmp/rundeck/ACLS/*
-      cp -rp /tmp/rundeck/ACLS/* /etc/rundeck/
-    fi
-
-
-
    if [ ! -f /etc/rundeck/ssl/truststore ]; then
-       echo "=>Gerando certificados ssl"
+       echo "=>Generating ssl cert"
        sudo -u rundeck mkdir -p /etc/rundeck/ssl
        if [ ! -f /etc/rundeck/ssl/keystore ]; then
            sudo -u rundeck keytool -importkeystore -destkeystore /etc/rundeck/ssl/keystore -srckeystore /etc/ssl/certs/java/cacerts -deststoretype JKS -srcstoretype JKS -deststorepass ${TRUSTSTORE_PASS} -srcstorepass changeit -noprompt > /dev/null
@@ -125,24 +90,20 @@ if [ ! -f "${initfile}" ]; then
        sudo -u rundeck keytool -keystore /etc/rundeck/ssl/keystore -alias rundeck -genkey -keyalg RSA -keypass ${KEYSTORE_PASS} -storepass ${TRUSTSTORE_PASS} -dname "cn=localhost, o=OME, c=DE"
        cp /etc/rundeck/ssl/keystore /etc/rundeck/ssl/truststore
    fi
-
-    
-    if [[ "${DATABASE_URL}" == *"mysql"* && "${SKIP_DATABASE_SETUP}" != "true" ]]; then
-      MYSQL_CNX_STRING=$(echo ${DATABASE_URL} | grep -oP "(?<=jdbc:mysql:\/\/)(.*)(?=\/)")
-      MYSQL_SERVER_NODE=${MYSQL_CNX_STRING}
-      MYSQL_SERVER_PORT=3306
-      echo ${MYSQL_CNX_STRING} | grep -q ':' && {
-        MYSQL_SERVER_NODE=$(echo ${MYSQL_CNX_STRING}|awk -F':' '{print $1}')
-        MYSQL_SERVER_PORT=$(echo ${MYSQL_CNX_STRING}|awk -F':' '{print $2}')
-          }
-          echo "=>Criando o banco de dados para o rundeck. Caso nao exista, claro"
-          (
-            echo "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
-            echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE, CREATE VIEW, ALTER, INDEX, EXECUTE ON ${MYSQL_DATABASE}.* TO '${RUNDECK_USER}'@'%' IDENTIFIED BY '${RUNDECK_PASSWORD}';"
-            echo "quit"
-            ) |
-        mysql --host=${MYSQL_SERVER_NODE} --port=${MYSQL_SERVER_PORT} --user=${DATABASE_ADMIN_USER} --password=${DATABASE_ADMIN_PASSWORD}
-    fi
+  MYSQL_CNX_STRING=$(echo ${DATABASE_URL} | grep -oP "(?<=jdbc:mysql:\/\/)(.*)(?=\/)")
+  MYSQL_SERVER_NODE=${MYSQL_CNX_STRING}
+  MYSQL_SERVER_PORT=3306
+  echo ${MYSQL_CNX_STRING} | grep -q ':' && {
+    MYSQL_SERVER_NODE=$(echo ${MYSQL_CNX_STRING}|awk -F':' '{print $1}')
+    MYSQL_SERVER_PORT=$(echo ${MYSQL_CNX_STRING}|awk -F':' '{print $2}')
+      }
+      echo "=>Initializing remote MySQL setup"
+      (
+        echo "CREATE DATABASE IF NOT EXISTS rundeckdb;"
+        echo "GRANT SELECT, INSERT, UPDATE, DELETE, DROP, CREATE, CREATE VIEW, ALTER, INDEX, EXECUTE ON rundeckdb.* TO '${RUNDECK_USER}'@'%' IDENTIFIED BY '${RUNDECK_PASSWORD}';"
+        echo "quit"
+        ) |
+    mysql --host=${MYSQL_SERVER_NODE} --port=${MYSQL_SERVER_PORT} --user=${DATABASE_ADMIN_USER} --password=${DATABASE_ADMIN_PASSWORD}
 
   if ! [ -z "${EXTERNAL_SERVER_URL}" ]; then
     # if external_server_url is specified, write it in
@@ -150,7 +111,7 @@ if [ ! -f "${initfile}" ]; then
   fi
 
    sed -i 's,dataSource.dbCreate.*,,g' /etc/rundeck/rundeck-config.properties
-   sed -i 's,dataSource.url = .*,dataSource.url = '${DATABASE_URL}',g' /etc/rundeck/rundeck-config.properties
+   sed -i 's,dataSource.url = .*,dataSource.url = '${DATABASE_URL//\&/\\\&}',g' /etc/rundeck/rundeck-config.properties
    if grep -q dataSource.driverClassName /etc/rundeck/rundeck-config.properties ; then
       sed -i 's,dataSource.driverClassName = .*,dataSource.driverClassName = '${DATABASE_DRIVER}',g' /etc/rundeck/rundeck-config.properties
    else
@@ -165,6 +126,15 @@ if [ ! -f "${initfile}" ]; then
       sed -i 's,dataSource.password = .*,dataSource.password = '${RUNDECK_PASSWORD}',g' /etc/rundeck/rundeck-config.properties
    else
       echo -e "\ndataSource.password = ${RUNDECK_PASSWORD}" >> /etc/rundeck/rundeck-config.properties
+   fi
+
+   # Check if we need to set the rundeck.gui.brand.html property
+   if [ -n "${GUI_BRAND_HTML}" ]; then
+      if grep -q rundeck.gui.brand.html /etc/rundeck/rundeck-config.properties ; then
+        sed -i 's/rundeck\.gui\.brand\.html.*$/rundeck\.gui\.brand\.html = '${GUI_BRAND_HTML}'/g' /etc/rundeck/rundeck-config.properties
+      else
+        echo "rundeck.gui.brand.html = ${GUI_BRAND_HTML}" >> /etc/rundeck/rundeck-config.properties
+      fi
    fi
 
    # Check if we need to set the grails.mail.host property
@@ -226,6 +196,13 @@ if [ ! -f "${initfile}" ]; then
    sed -i 's,framework.server.hostname\ \=.*,framework.server.hostname\ \=\ '${SERVER_HOSTNAME}',g' /etc/rundeck/framework.properties
    sed -i 's,framework.server.port\ \=.*,framework.server.port\ \=\ '${SERVER_PORT}',g' /etc/rundeck/framework.properties
    sed -i 's,framework.server.url\ \=.*,framework.server.url\ \=\ '${SERVER_URL}',g' /etc/rundeck/framework.properties
+   if [ -n "${RUNDECK_SERVER_UUID}" ]; then
+      if grep -q rundeck.server.uuid /etc/rundeck/framework.properties ; then
+        sed -i 's/rundeck\.server\.uuid.*$/rundeck\.server\.uuid = '${RUNDECK_SERVER_UUID}'/g' /etc/rundeck/framework.properties
+      else
+        echo "quartz.threadPool.threadCount = ${RUNDECK_THREAD_COUNT}" >> /etc/rundeck/rundeck-config.properties
+      fi
+   fi
 
    # if the admin pwd is still the default password and RUNDECK_ADMIN_PASSWORD is defined
    if $(grep --silent '^admin:admin,' /etc/rundeck/realm.properties) && [[ -n "${RUNDECK_ADMIN_PASSWORD}" ]]; then
@@ -252,24 +229,36 @@ if [ ! -f "${initfile}" ]; then
       else
         echo "rundeck.storage.provider.1.type=db" >> /etc/rundeck/rundeck-config.properties
       fi
-      if grep -q rundeck.storage.provider.1.path /etc/rundeck/rundeck-config.properties ; then
+      if grep -q rundeck.config.storage.converter.1.path /etc/rundeck/rundeck-config.properties ; then
         :
       else
-        echo "rundeck.storage.provider.1.path=/" >> /etc/rundeck/rundeck-config.properties
+        echo "rundeck.config.storage.converter.1.path=/" >> /etc/rundeck/rundeck-config.properties
+      fi
+      if ! [ -z "${RUNDECK_STORAGE_PASSWORD}" ]; then
+        if grep -q rundeck.storage.converter.1.config.password /etc/rundeck/rundeck-config.properties ; then
+          sed -i 's/rundeck\.storage\.converter\.1\.config\.password.*$/rundeck\.storage\.converter\.1\.config\.password='${RUNDECK_STORAGE_PASSWORD}'/g' /etc/rundeck/rundeck-config.properties
+        else
+          echo "rundeck.storage.converter.1.config.password=${RUNDECK_STORAGE_PASSWORD}" >> /etc/rundeck/rundeck-config.properties
+        fi
+        if grep -q rundeck.config.storage.converter.1.config.password /etc/rundeck/rundeck-config.properties ; then
+          sed -i 's/rundeck\.config\.storage\.converter\.1\.config\.password.*$/rundeck\.config\.storage\.converter\.1\.config\.password='${RUNDECK_STORAGE_PASSWORD}'/g' /etc/rundeck/rundeck-config.properties
+        else
+          echo "rundeck.config.storage.converter.1.config.password=${RUNDECK_STORAGE_PASSWORD}" >> /etc/rundeck/rundeck-config.properties
+        fi
       fi
    fi
 
-   if [ "${RUNDECK_PROJECT_STORAGE_TYPE}" == "db" ]; then
-      if grep -q rundeck.projectsStorageType /etc/rundeck/rundeck-config.properties ; then
-        sed -i 's/rundeck\.projectsStorageType.*$/rundeck\.projectsStorageType='${RUNDECK_PROJECT_STORAGE_TYPE}'/g' /etc/rundeck/rundeck-config.properties
+   if [ -n "${RUNDECK_SERVER_UUID}" ]; then
+      if grep -q rundeck.server.uuid /etc/rundeck/framework.properties ; then
+        sed -i 's,rundeck.server.uuid \=.*,rundeck.server.uuid \= '${RUNDECK_SERVER_UUID}',g' /etc/rundeck/framework.properties
       else
-        echo "rundeck.projectsStorageType=db" >> /etc/rundeck/rundeck-config.properties
+        echo "rundeck.server.uuid = ${RUNDECK_SERVER_UUID}" >> /etc/rundeck/framework.properties
       fi
    fi
 
    if [ "${CLUSTER_MODE}" == "true" ]; then
       echo "rundeck.clusterMode.enabled=true" >> /etc/rundeck/rundeck-config.properties
-    sed -i 's,rundeck.server.uuid \=.*,rundeck.server.uuid \= '$(uuidgen)',g' /etc/rundeck/framework.properties
+      sed -i 's,rundeck.server.uuid \=.*,rundeck.server.uuid \= '$(uuidgen)',g' /etc/rundeck/framework.properties
    fi
 
    sed -i 's,JAAS_CONF\=.*,JAAS_CONF\="/etc/rundeck/'${JAAS_CONF_FILE}'",' /etc/rundeck/profile
@@ -280,22 +269,23 @@ if [ ! -f "${initfile}" ]; then
 
    # Generate the system wide locales in the background.
    # It may take a long time, depending on the mounted /etc/locale.gen.
-   # The only part, where locale processing is known to be necessary, is
-   # the Icingaweb2 translation plugin and locale-gen should be finished
-   # until the first webpage is started.
    locale-gen &
 
    echo -e "\n\n\n"
    echo "==================================================================="
-   echo "MySQL user setado para '${RUNDECK_USER}' | senha setada para ${RUNDECK_PASSWORD}"
-   echo "Rundeck project storage setado para ${RUNDECK_PROJECT_STORAGE_TYPE}"
-   echo "Rundeck Storage provider setado para ${RUNDECK_STORAGE_PROVIDER}"
-   echo "Rundeck public key configurada:"
+   if [ "${NO_LOCAL_MYSQL}" == "true" ]; then
+      echo "NO_LOCAL_MYSQL set to true so local MySQL has not been configured or started"
+   else
+      echo "MySQL user 'root' has no password but only allows local connections"
+   fi
+   echo "MySQL user '${RUNDECK_USER}' password set to ${RUNDECK_PASSWORD}"
+   echo "Rundeck Storage provider set to ${RUNDECK_STORAGE_PROVIDER}"
+   echo "Rundeck public key:"
    cat /var/lib/rundeck/.ssh/id_rsa.pub
    if ! [ -z "${EXTERNAL_SERVER_URL}" ]; then
-      echo "Server URL  ${EXTERNAL_SERVER_URL}"
+      echo "Server URL set to ${EXTERNAL_SERVER_URL}"
    else
-      echo "Server URL ${SERVER_URL}"
+      echo "Server URL set to ${SERVER_URL}"
    fi
 
    echo "==================================================================="
@@ -304,10 +294,10 @@ if [ ! -f "${initfile}" ]; then
 fi
 
 echo -e "\n"
-echo "Iniciando Supervisor..."
-echo "Isso pode levar pelo menos 30 segundos"
-echo "A interface pode levar alguns minutos para ficar disponivel"
-echo "Daqui pra baixo, apenas outputs stdout/stderr do processo do supervisor."
+echo "Starting Supervisor..."
+echo "It can take anywhere from 30 seconds up to a few minutes for the UI"
+echo "to become available depending on your container/host VM resources."
+echo "All further output is stdout/stderr from the supervisor process."
 echo -e "\n"
 
 /usr/bin/supervisord -c /etc/supervisor/supervisord.conf -n &
